apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: http-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2020
        startupProbe:
          httpGet:
            path: /health
            port: 2020
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  selector:
    app: http-server
  type: NodePort
  ports:
    - name: http
      port: 2020
      targetPort: 2020